spring:
  application:
    name: PaymentServiceDemo

  datasource:
    url: jdbc:mysql://localhost:3306/paymentService
    username: root
    password: shameer
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  logging:
    level:
      org.hibernate.SQL: DEBUG

server:
  port: 9094

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:9095/eureka
    register-with-eureka: true
    fetch-registry: true
